plan:
  defaultOnStartup: false
async:
  enabled: false
task:
  batch: false
  enableEffort: false
  maxConcurrency: 1
  maxRecursionDepth: 2
  maxRuntimeMs: 180000
  isolation:
    mode: none
    apply: false
